name: Compile gas mixer doc
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: LaTeX compilation
      # You may pin to the exact commit or the version.
      # uses: dante-ev/latex-action@49cf7cb5f79e7b2006dbdffea85e02bec0b6244b
      uses: dante-ev/latex-action@2021-A
      with:
        root_file: furnace-mixer-doc-2.tex
        working_directory: factory/smelting/gas-mixer-doc/
        compiler: lualatex
        args: -interaction=nonstopmode -shell-escape
